export const fallbackCourses = [
  {
    _id: "1",
    title: "Absolute Zero Basics",
    language: "Computer Fundamentals",
    level: "Beginner",
    duration: "4 Weeks",
    description: "Mouse, keyboard, files, internet, and everyday computer confidence from scratch.",
    accent: "from-emerald-500/20 to-teal-500/10",
    badge: "Start Here",
  },
  {
    _id: "2",
    title: "Java Programming",
    language: "Java",
    level: "Intermediate",
    duration: "8 Weeks",
    description: "OOP, collections, JDBC, and real-world backend patterns used in enterprise apps.",
    accent: "from-orange-500/20 to-amber-500/10",
    badge: "Popular",
  },
  {
    _id: "3",
    title: "Python for Everyone",
    language: "Python",
    level: "Beginner → Advanced",
    duration: "10 Weeks",
    description: "Scripting, data handling, automation, and foundations for AI & data science.",
    accent: "from-blue-500/20 to-cyan-500/10",
    badge: "Versatile",
  },
  {
    _id: "4",
    title: "Full-Stack Development",
    language: "MERN Stack",
    level: "Advanced",
    duration: "16 Weeks",
    description: "React, Node.js, APIs, databases, auth, and deployment — build production apps.",
    accent: "from-accentViolet/25 to-violet-950/15",
    badge: "Career Track",
  },
  {
    _id: "5",
    title: "Web Foundations",
    language: "HTML · CSS · JS",
    level: "Beginner",
    duration: "6 Weeks",
    description: "Responsive layouts, modern CSS, and interactive JavaScript for the open web.",
    accent: "from-pink-500/20 to-rose-500/10",
    badge: "Essential",
  },
  {
    _id: "6",
    title: "Database & SQL",
    language: "MySQL / PostgreSQL",
    level: "Intermediate",
    duration: "5 Weeks",
    description: "Schema design, queries, joins, indexing, and data modeling for real applications.",
    accent: "from-yellow-500/20 to-orange-500/10",
    badge: "Core Skill",
  },
];
